#ifndef __QUEUE_ERR_H__
#define __QUEUE_ERR_H__

typedef enum
{
	ERR_QUEUE_OK,
	ERR_QUEUE_GENERAL,
	ERR_QUEUE_NOT_INITIALIZED,
	ERR_QUEUE_ALOCATION_FAILED,
	ERR_QUEUE_REALOCATION_FAILED,
	ERR_QUEUE_UNDERFLOW,
	ERR_QUEUE_OVERFLOW,
	ERR_QUEUE_WRONG_INDEX,
	ERR_QUEUE_EMPTY
}  QueueErr;


#endif	/* #ifndef __QUEUE_ERR_H__ */
