#ifndef _ADTERR_H_
#define _ADTERR_H_

typedef enum {
	VECTOR_OK,
	VECTOR_NOT_INITIALIZED,
	VECTOR_ALLOCATION_FAILED,
	VECTOR_REALLOCATION_FAILED,
	VECTOR_UNDERFLOW,
	VECTOR_OVERFLOW,
	VECTOR_WRONG_INDEX
} Vector_StatusCode ;


#endif	/* #ifndef _ADTERR_H_ */
